version: "3"
services:
  cartao_db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: cartao
      POSTGRES_USER: cartao
      POSTGRES_DB: cartao
    ports:
      - "5433:5432"
  spring-boot-jpa-docker-webapp:
    image: gradle-springboot
    depends_on:
      - cartao_db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=cartao_db
      - DATABASE_USER=cartao
      - DATABASE_PASSWORD=cartao
      - DATABASE_NAME=cartao
      - DATABASE_PORT=5432

volumes:
  db-data:
    driver: local